CREATE TABLE IF NOT EXISTS posts (
    no BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    views INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS POST_TAGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_NO BIGINT NOT NULL,
    TAG_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT FK_POST_TAGS_POST_NO FOREIGN KEY (POST_NO) REFERENCES posts(no) ON DELETE CASCADE
);
